export const emptyStats = {
  allTasks: 0,
  pending: 0,
  inProgress: 0,
  completed: 0,
  overdue: 0,
  noDeadline: 0,
  dueToday: 0,
};

export const statusOptions = ["pending", "in progress", "completed"];

export const sortOptions = [
  { value: "deadline", label: "Deadline" },
  { value: "newest", label: "Newest" },
  { value: "oldest", label: "Oldest" },
  { value: "status", label: "Status" },
];

const styles = {
  page: {
    minHeight: "100vh",
    background:
      "linear-gradient(180deg, #f8fbff 0%, #eef5ff 55%, #f7fbff 100%)",
    padding: "32px 20px",
  },
  shell: {
    maxWidth: "1320px",
    margin: "0 auto",
    display: "grid",
    gap: "24px",
  },
  hero: {
    background:
      "linear-gradient(135deg, #0f172a 0%, #1d4ed8 52%, #38bdf8 100%)",
    color: "#ffffff",
    borderRadius: "28px",
    padding: "30px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 2fr) minmax(280px, 1fr)",
    gap: "24px",
    alignItems: "stretch",
    boxShadow: "0 24px 55px rgba(15, 23, 42, 0.24)",
  },
  heroTitle: {
    fontSize: "34px",
    fontWeight: 800,
    lineHeight: 1.2,
    marginBottom: "12px",
  },
  heroText: {
    color: "rgba(255, 255, 255, 0.86)",
    lineHeight: 1.6,
    maxWidth: "720px",
  },
  chipRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    marginTop: "18px",
  },
  chip: {
    padding: "9px 14px",
    borderRadius: "999px",
    background: "rgba(255, 255, 255, 0.14)",
    color: "#ffffff",
    fontSize: "14px",
  },
  heroSide: {
    background: "rgba(255, 255, 255, 0.14)",
    borderRadius: "22px",
    padding: "22px",
    display: "grid",
    gap: "14px",
    alignContent: "start",
  },
  sideTitle: {
    fontSize: "18px",
    fontWeight: 700,
  },
  sideMetric: {
    fontSize: "36px",
    fontWeight: 800,
    lineHeight: 1,
  },
  sideText: {
    color: "rgba(255, 255, 255, 0.82)",
    lineHeight: 1.5,
  },
  buttonRow: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  },
  primaryButton: {
    border: "none",
    borderRadius: "12px",
    padding: "12px 18px",
    background: "#2563eb",
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
  },
  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "12px 18px",
    background: "#ffffff",
    color: "#0f172a",
    fontWeight: 700,
    cursor: "pointer",
  },
  ghostButton: {
    border: "1px solid rgba(255, 255, 255, 0.35)",
    borderRadius: "12px",
    padding: "12px 18px",
    background: "transparent",
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
  },
  message: {
    borderRadius: "14px",
    padding: "14px 16px",
    border: "1px solid #bfdbfe",
    background: "#eff6ff",
    color: "#1d4ed8",
  },
  error: {
    background: "#fef2f2",
    color: "#b91c1c",
    border: "1px solid #fecaca",
    borderRadius: "14px",
    padding: "14px 16px",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))",
    gap: "16px",
  },
  statCard: {
    background: "#ffffff",
    borderRadius: "22px",
    padding: "20px",
    border: "1px solid #dbe5f1",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
  },
  statLabel: {
    color: "#64748b",
    fontSize: "14px",
    marginBottom: "10px",
  },
  statValue: {
    color: "#0f172a",
    fontSize: "32px",
    fontWeight: 800,
  },
  statHint: {
    color: "#64748b",
    fontSize: "13px",
    marginTop: "8px",
  },
  activityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: "18px",
  },
  panel: {
    background: "#ffffff",
    borderRadius: "22px",
    padding: "22px",
    border: "1px solid #dbe5f1",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
  },
  panelTitle: {
    fontSize: "22px",
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: "8px",
  },
  panelText: {
    color: "#64748b",
    marginBottom: "18px",
    lineHeight: 1.5,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: "999px",
    background: "#dbeafe",
    color: "#1d4ed8",
    fontSize: "12px",
    fontWeight: 700,
  },
  warningBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: "999px",
    background: "#fef3c7",
    color: "#b45309",
    fontSize: "12px",
    fontWeight: 700,
  },
  dangerBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: "999px",
    background: "#fee2e2",
    color: "#b91c1c",
    fontSize: "12px",
    fontWeight: 700,
  },
  activityCard: {
    display: "grid",
    gap: "12px",
  },
  progressBarTrack: {
    width: "100%",
    height: "12px",
    borderRadius: "999px",
    background: "#dbeafe",
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: "999px",
    background: "linear-gradient(90deg, #2563eb 0%, #38bdf8 100%)",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "24px",
    alignItems: "start",
  },
  form: {
    display: "grid",
    gap: "14px",
  },
  label: {
    display: "grid",
    gap: "8px",
    color: "#334155",
    fontSize: "14px",
    fontWeight: 700,
  },
  input: {
    width: "100%",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "12px 14px",
    fontSize: "14px",
    outline: "none",
    background: "#ffffff",
  },
  textarea: {
    width: "100%",
    minHeight: "110px",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "12px 14px",
    fontSize: "14px",
    resize: "vertical",
    outline: "none",
    background: "#ffffff",
  },
  select: {
    border: "1px solid #cbd5e1",
    borderRadius: "10px",
    padding: "10px 12px",
    background: "#ffffff",
  },
  quickGrid: {
    display: "grid",
    gap: "14px",
    marginTop: "20px",
  },
  quickCard: {
    background: "#f8fbff",
    border: "1px solid #dbe5f1",
    borderRadius: "18px",
    padding: "16px",
  },
  quickTitle: {
    color: "#0f172a",
    fontSize: "16px",
    fontWeight: 700,
    marginBottom: "6px",
  },
  quickText: {
    color: "#64748b",
    lineHeight: 1.5,
    fontSize: "14px",
  },
  toolbar: {
    display: "grid",
    gridTemplateColumns: "minmax(180px, 1.4fr) repeat(2, minmax(130px, 180px))",
    gap: "12px",
    marginBottom: "18px",
  },
  filterRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    marginBottom: "18px",
  },
  filterButton: {
    borderRadius: "999px",
    padding: "9px 14px",
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#334155",
    cursor: "pointer",
    fontWeight: 600,
  },
  activeFilterButton: {
    borderRadius: "999px",
    padding: "9px 14px",
    border: "1px solid #2563eb",
    background: "#dbeafe",
    color: "#1d4ed8",
    cursor: "pointer",
    fontWeight: 700,
  },
  taskList: {
    display: "grid",
    gap: "16px",
  },
  taskCard: {
    borderRadius: "20px",
    padding: "18px",
    background: "#f8fbff",
    border: "1px solid #dbe5f1",
  },
  taskTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "12px",
    flexWrap: "wrap",
  },
  taskTitle: {
    fontSize: "18px",
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: "6px",
  },
  taskMeta: {
    color: "#64748b",
    fontSize: "14px",
    lineHeight: 1.5,
  },
  taskDescription: {
    color: "#334155",
    marginTop: "12px",
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
  },
  taskActions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: "16px",
  },
  actionButton: {
    border: "1px solid #cbd5e1",
    borderRadius: "10px",
    padding: "10px 14px",
    background: "#ffffff",
    color: "#0f172a",
    fontWeight: 600,
    cursor: "pointer",
  },
  deleteButton: {
    border: "none",
    borderRadius: "10px",
    padding: "10px 14px",
    background: "#dc2626",
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
  },
  emptyState: {
    border: "1px dashed #cbd5e1",
    borderRadius: "18px",
    padding: "28px",
    textAlign: "center",
    color: "#64748b",
    background: "#f8fbff",
  },
  timeline: {
    display: "grid",
    gap: "14px",
  },
  timelineItem: {
    display: "grid",
    gap: "6px",
    padding: "14px 0",
    borderBottom: "1px solid #e2e8f0",
  },
  timelineTitle: {
    fontSize: "15px",
    fontWeight: 700,
    color: "#0f172a",
  },
  timelineMeta: {
    fontSize: "13px",
    color: "#64748b",
  },
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.45fr) minmax(280px, 0.9fr)",
    gap: "24px",
    alignItems: "start",
  },
};

export default styles;
